### ISSUE TITLE
这个地方的显示似乎有点问题？

### ISSUE THREAD

**Issue by lovimnnqbi** [lovegaoshi/NoxPlayer#100]
大佬，这个地方的显示是不是有点问题？
![image](https://github.com/user-attachments/assets/e234048b-5e23-4290-ac89-fd154eb05c9d)
我安装了一下[电梓播放器](https://microsoftedge.microsoft.com/addons/detail/%E7%94%B5%E6%A2%93%E6%92%AD%E6%94%BE%E5%99%A8%E7%AC%AC%E4%B8%89%E6%96%B9bilibili%E9%9F%B3%E9%A2%91%E6%92%AD%E6%94%BE%E5%99%A8/bikfgaolchpolficinadmbmkkohkbkdf)的插件看了一下这里的显示是没问题的：
![image](https://github.com/user-attachments/assets/007e5f5d-9a63-4963-b483-a880b984b27a)
我的使用环境：
- 操作系统：win10
- 浏览器：Edge
---------
如果这是一个bug恳请大佬有时间了能修一下🙏，插件真的很好用👍🏻

**Comment by lovegaoshi** [comment]
closed by https://github.com/lovegaoshi/NoxPlayer/pull/101
