### ISSUE TITLE
蛙吹keroro皮肤只有插件版的；；

### ISSUE THREAD

**Issue by nekoword420** [lovegaoshi/NoxPlayer#64]
只做了插件版的皮肤应该也可以吧？
[蛙蛙skill.zip](https://github.com/lovegaoshi/NoxPlayer/files/15047947/skill.zip)

**Comment by lovegaoshi** [comment]
蛙蛙有装扮阿，好办
#bedbed不是蓝的吗？这不得像赫拉kris那样整个绿的

**Comment by lovegaoshi** [comment]
![Uploading Screenshot_20240420_050958_APM.jpg…]()

**Comment by lovegaoshi** [comment]
配色为么是蓝的，我以为应该是绿的？
![Screenshot_20240420_050958_APM](https://github.com/lovegaoshi/NoxPlayer/assets/106490582/97824bc6-e818-4e96-abdc-03f2e3aad03c)

**Comment by nekoword420** [comment]
因为蓝色是杠杠的颜色（偷偷埋一手

**Comment by lovegaoshi** [comment]
就大概这个样子
![image](https://github.com/lovegaoshi/NoxPlayer/assets/106490582/0fd8a346-399f-420a-aeb3-65734720fdeb)

**Comment by nekoword420** [comment]
嗯差不多就是这个感觉
