### ISSUE TITLE
搜索功能出错

### ISSUE THREAD

**Issue by 1235689hhh** [lovegaoshi/NoxPlayer#75]
我使用b站url来进行搜索,然而搜索结果出现了错误,一个不知道从哪里来的歌单
![image](https://github.com/lovegaoshi/NoxPlayer/assets/73057863/01e33543-9642-4d4b-aa95-36803212ace6)
,然后我尝试搜索"1",结果这个根本不是url的搜索内容搜索到了一个完全未知的歌单,并且与之前我搜索到的歌单不同
![image](https://github.com/lovegaoshi/NoxPlayer/assets/73057863/0103c5da-5558-4802-a4f5-124bd1acdcb8)
我认为这是一个恶性的bug,如果是一个特性,我希望得到解释

**Comment by lovegaoshi** [comment]
你不贴url怎么修啊

nox 支持关键字搜索 你打1相当于在b站搜索1 然后返回前40个条目
不然你搜索周杰伦看看

**Comment by 1235689hhh** [comment]
原来是直接搜索吗,懂了,谢谢解答,应该是我的链接不符合规范导致的,没事了
