### ISSUE TITLE
Chrome Store 不更新了么

### ISSUE THREAD

**Issue by wenhairu** [lovegaoshi/NoxPlayer#92]
rt

**Comment by lovegaoshi** [comment]
nox只在[edge](https://microsoftedge.microsoft.com/addons/detail/%E7%94%B5%E9%97%B9%E6%92%AD%E6%94%BE%E5%99%A8/jlhdkgcfcdabihmdkhdjlcppdlnlfogp)更新
在chrome更新的电梓播放器跑路了
