### ISSUE TITLE
新版本出现问题，

### ISSUE THREAD

**Issue by bwcd-123** [lovegaoshi/NoxPlayer#96]
版本4.1.0.0

停留在loading界面，无法使用

控制台错误信息
popup.js:75  Uncaught (in promise) TypeError: object is not iterable (cannot read property Symbol(Symbol.iterator))
    at new Map (<anonymous>)
    at popup.js:75:229389
    at k (popup.js:82:287274)
    at async D (popup.js:75:229352)
    at async r (popup.js:82:5857)
    at async popup.js:82:2955

使用老版本4.0.3.0没有问题

![QQ20240821-163139](https://github.com/user-attachments/assets/2ff72650-7b10-4b5d-8057-6d48633a9cea)

**Comment by lovegaoshi** [comment]
本地歌单备份能上传一下吗

**Comment by lovegaoshi** [comment]
fixed by #97
