### ISSUE TITLE
最新版无法播放音频

### ISSUE THREAD

**Issue by kunger97** [lovegaoshi/NoxPlayer#98]
版本：4.1.1.0（Chrome插件列表显示），实际是下载的[Unpacked v4.1.1](https://github.com/lovegaoshi/NoxPlayer/releases/tag/v4.1.1)
选择任何歌单点击歌单中的音乐均无法播放。表现为无限跳下一首。
控制台报错如下图
![QQ20240923-195025](https://github.com/user-attachments/assets/a45bfb52-e920-4bf4-b0f6-1e6ab298e9b6)

**Comment by lovegaoshi** [comment]
![image](https://github.com/user-attachments/assets/16a8f860-9875-4154-bf6b-ca718b78bb73)

没法复现
麻烦点击 右键 开发者工具 网络 再点击歌 查看playurl这个请求

![image](https://github.com/user-attachments/assets/93a453ae-9272-411c-ab85-3dfe4ff18c5c)

**Comment by kunger97** [comment]
![image](https://github.com/user-attachments/assets/824412aa-cb53-4bb5-bc48-28bbdbe15245)

**Comment by lovegaoshi** [comment]
应该是你的ip或b号 被风控了
